#!/bin/bash
#
# Set up the hackathon data directory for EST Adapter
#
# Creates the complete data directory structure with:
# - Generated certificates (CA, server TLS with VPN IP, test certs)
# - Pre-configured config.yaml pointing to container paths
# - Empty db/ and logs/ directories
#
# Usage: ./setup-hackathon.sh <vpn-ip> [data_dir]
#
# Example:
#   ./setup-hackathon.sh 10.8.0.5
#   ./setup-hackathon.sh 10.8.0.5 ./my-data
#
# After running:
#   docker compose up -d
#   # or:
#   docker run -v $(pwd)/data:/data/est-adapter -p 8443:8443 est-adapter
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

VPN_IP="${1:?Usage: $0 <vpn-ip> [data_dir]}"
DATA_DIR="${2:-$PROJECT_DIR/data}"

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_step()  { echo -e "${CYAN}▶${NC} $1"; }

log_info "Setting up hackathon data directory: $DATA_DIR"
log_info "VPN IP: $VPN_IP"

# =============================================================================
# Create directory structure
# =============================================================================
log_step "Creating directory structure..."
mkdir -p "$DATA_DIR/est-adapter/certs/ca"
mkdir -p "$DATA_DIR/est-adapter/certs/tls"
mkdir -p "$DATA_DIR/est-adapter/certs/trust"
mkdir -p "$DATA_DIR/est-adapter/certs/test"
mkdir -p "$DATA_DIR/est-adapter/db"
mkdir -p "$DATA_DIR/est-adapter/logs"

# =============================================================================
# Generate certificates
# =============================================================================
log_step "Generating certificates..."
"$SCRIPT_DIR/generate-certs.sh" "$VPN_IP" "$DATA_DIR/est-adapter/certs"

# =============================================================================
# Generate bcrypt password hash for default user
# =============================================================================
log_step "Generating default auth credentials..."

# Generate bcrypt hash using the project's virtual environment
DEFAULT_PASSWORD="hackathon2026"
PASSWORD_HASH=$(cd "$PROJECT_DIR" && uv run python3 -c "import bcrypt; print(bcrypt.hashpw(b'$DEFAULT_PASSWORD', bcrypt.gensalt()).decode())" 2>/dev/null || \
    python3 -c "import bcrypt; print(bcrypt.hashpw(b'$DEFAULT_PASSWORD', bcrypt.gensalt()).decode())" 2>/dev/null || \
    echo '$2b$12$placeholder.hash.replace.me.with.real.bcrypt.hash')

# =============================================================================
# Generate config.yaml for container paths
# =============================================================================
log_step "Generating config.yaml..."

cat > "$DATA_DIR/est-adapter/config.yaml" << EOF
# EST Adapter Configuration — Hackathon Setup
# Generated by setup-hackathon.sh for VPN IP: $VPN_IP
#
# All paths reference /data/est-adapter/ (the container mount point)

server:
  host: "0.0.0.0"
  port: 8443
  tls:
    cert_file: /data/est-adapter/certs/tls/server.crt
    key_file: /data/est-adapter/certs/tls/server.key

ca:
  # Use the generated CA (already created by setup script)
  mode: provided
  provided:
    cert_file: /data/est-adapter/certs/ca/ca.crt
    key_file: /data/est-adapter/certs/ca/ca.key

auth:
  method: basic
  basic:
    users:
      - username: device1
        password_hash: "$PASSWORD_HASH"
      - username: hackathon
        password_hash: "$PASSWORD_HASH"
  # Uncomment for mTLS authentication:
  # method: both
  # client_cert:
  #   trust_anchors: /data/est-adapter/certs/trust/ca-trust.pem

validation:
  min_key_size: 2048
  allowed_key_types:
    - RSA
    - EC
  allowed_ec_curves:
    - secp256r1
    - secp384r1
  max_validity_days: 365
  required_subject_fields:
    - CN
  subject_cn_pattern: "^[a-zA-Z0-9._-]+$"

audit:
  log_file: /data/est-adapter/logs/audit.log
  log_level: INFO

admin:
  enabled: true
  api:
    enabled: true
    port: 8080
    host: "0.0.0.0"
  database:
    url: "sqlite+aiosqlite:////data/est-adapter/db/est_adapter.db"
    pool_size: 10
    max_overflow: 20
EOF

# =============================================================================
# Summary
# =============================================================================
echo ""
echo -e "${BOLD}=========================================="
echo "  Hackathon Setup Complete!"
echo -e "==========================================${NC}"
echo ""
echo "Data directory: $DATA_DIR/est-adapter/"
echo ""
echo -e "${BOLD}Default credentials:${NC}"
echo "  Username: device1  (or: hackathon)"
echo "  Password: $DEFAULT_PASSWORD"
echo ""
echo -e "${BOLD}To start with Docker Compose:${NC}"
echo "  cd $PROJECT_DIR"
echo "  docker compose up -d"
echo ""
echo -e "${BOLD}To start with docker run:${NC}"
echo "  docker run -v $DATA_DIR:/data -p 8443:8443 -p 8080:8080 est-adapter"
echo ""
echo -e "${BOLD}To test:${NC}"
echo "  # Health check"
echo "  curl -k https://$VPN_IP:8443/health"
echo ""
echo "  # Get CA certificates"
echo "  curl -k https://$VPN_IP:8443/.well-known/est/cacerts"
echo ""
echo "  # Enroll (with test CSR)"
echo "  curl -k -X POST https://$VPN_IP:8443/.well-known/est/simpleenroll \\"
echo "    -u device1:$DEFAULT_PASSWORD \\"
echo "    -H 'Content-Type: application/pkcs10' \\"
echo "    --data-binary @$DATA_DIR/est-adapter/certs/test/enroll-device.b64"
echo ""
echo -e "${BOLD}To run the full demo:${NC}"
echo "  $SCRIPT_DIR/demo-enrollment.sh $VPN_IP"
